name: String Parser

on:
  workflow_dispatch:

jobs:
  parse-string:
    runs-on: ubuntu-latest

    steps:
      - name: Run string parser
        uses: Team-B1ND/string-parser@v1
        with:
          body: "<Student>\n릴리즈 노트 작성\n<Teacher>\n릴리즈 노트 작성"
          split: "<Teacher>"
          splitIndex: 0
          envName: TEST

      - name: Output result
        run: echo "Parsed result ${{ env.TEST }}"